CREATE USER jerrod_anderson WITH ENCRYPTED PASSWORD 'yakowaga';
CREATE DATABASE jerrod_anderson WITH OWNER jerrod_anderson;
CREATE USER daisy_bell WITH ENCRYPTED PASSWORD 'gakehere';
CREATE DATABASE daisy_bell WITH OWNER daisy_bell;
CREATE USER matthias_dean WITH ENCRYPTED PASSWORD 'rekepici';
CREATE DATABASE matthias_dean WITH OWNER matthias_dean;
CREATE USER mitch_dejong WITH ENCRYPTED PASSWORD 'hilulayu';
CREATE DATABASE mitch_dejong WITH OWNER mitch_dejong;
CREATE USER caleb_fox WITH ENCRYPTED PASSWORD 'dusavede';
CREATE DATABASE caleb_fox WITH OWNER caleb_fox;
CREATE USER jacob_haimes WITH ENCRYPTED PASSWORD 'fugebiqa';
CREATE DATABASE jacob_haimes WITH OWNER jacob_haimes;
CREATE USER zachery_huse WITH ENCRYPTED PASSWORD 'wofayugi';
CREATE DATABASE zachery_huse WITH OWNER zachery_huse;
CREATE USER kendall_miyakawa WITH ENCRYPTED PASSWORD 'qemorude';
CREATE DATABASE kendall_miyakawa WITH OWNER kendall_miyakawa;
CREATE USER grace_rose WITH ENCRYPTED PASSWORD 'gokememe';
CREATE DATABASE grace_rose WITH OWNER grace_rose;
CREATE USER joseph_vanderharst WITH ENCRYPTED PASSWORD 'zupisoku';
CREATE DATABASE joseph_vanderharst WITH OWNER joseph_vanderharst;
CREATE USER qiang_wang WITH ENCRYPTED PASSWORD 'nuhonolo';
CREATE DATABASE qiang_wang WITH OWNER qiang_wang;
CREATE USER grace_weeks WITH ENCRYPTED PASSWORD 'serigiyu';
CREATE DATABASE grace_weeks WITH OWNER grace_weeks;
